version: "3"
services:
  app:
    container_name: mp
    restart: always
    env_file:
      - ./.env
    build: .
    ports:
      - "${PORT}:${PORT}"
    networks:
    - caddy
networks:
  caddy:
    external: true